# Generated by Django 5.2.10 on 2026-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('client', 'Client'), ('freelancer', 'Freelancer')], default='client', max_length=20),
        ),
    ]
